# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

# 日志配置
logging:
  level:
    com.tongchuang: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认一天）
  expireTime: 1440

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.tongchuang.huangshan.model.**.domain.admin
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml